### PR TITLE
support listing database views

### PR DESCRIPTION
**Pull request by landicefu**
Database views are very useful, and I found that using PRAGMA table_info can correctly list columns from a database view.

### CODE REVIEW

**Comment by vinayagasundar** [comment]
@landicefu Can you hide the Edit & Delete option for views in the html. because we can't do these operation on views .

**Comment by landicefu** [comment]
Ok, will do it later. This for the suggestion.

**Comment by landicefu** [comment]
@vinayagasundar It's done. Can you help to check? The code works, but I'm not so familiar with javascript. I hope the coding style is okay.

**Comment by vinayagasundar** [comment]
@landicefu Your code works well but it's breaking in Preferences CRUD operation. 
Can you check it ? 

@amitshekhariitbhu

**Comment by landicefu** [comment]
@vinayagasundar Right. I forgot to check if isEditable is set for preference.
It's updated.

**Comment by vinayagasundar** [comment]
@landicefu Nice work 
@amitshekhariitbhu Please accept this request

**Comment by amitshekhariitbhu** [comment]
@landicefu Thanks for the contribution.
@vinayagasundar Thanks for the verification.

Thanks
Amit Shekhar

**Pull request merged**
