### PR TITLE
Added SqlCipher support

### PR DESCRIPTION
**Pull request by mstarita**
Very quick integration with Sqlcipher.
Basically I've changed the map of Database file list from Map<String, File> to Map<String, Pair<File, String>> where the last string is the database password.

This is my little contribution to this useful project ;)

Marco

### CODE REVIEW

**Comment by amitshekhariitbhu** [comment]
@mstarita How to set the password for the database located at the default path?

**Comment by mstarita** [comment]
@amitshekhariitbhu Actually my focus on Sqlcipher was on external database file. So by now no way to setup the password for databases on default path.

**Comment by mstarita** [comment]
@amitshekhariitbhu I have addedd the password support for database on the default path (via resource string, see the build.gradle of the app module), a sample database with encryption and a lock icon on the web ui

**Comment by amitshekhariitbhu** [comment]
@mstarita : Great we will check and merge it in our new release.

**Pull request merged**
