### PR TITLE
Added option to export database

### PR DESCRIPTION
**Pull request by vinayagasundar**
#18  Added a option to download selected database from mobile.

### CODE REVIEW

**Comment by amitshekhariitbhu** [comment]
Thanks for your contribution. I will be merging and making it live in the new version.

**Comment by vinayagasundar** [comment]
@amitshekhariitbhu I've added proguard for library. So if the user enable proguard in their project in that case also it'll work without any issue. I think it's releated to #12

**Comment by amitshekhariitbhu** [comment]
@vinayagasundar nice work

**Comment by vinayagasundar** [comment]
Fixed #27

**Pull request merged**
