### PR TITLE
Help to fix Issue #50 - Reduce horizontal scrolling on web page, and show more content

### PR DESCRIPTION
**Pull request by ozmium**
1. Clarify button text to download database file. Change text: "Export Selected Database : " to **"Click here to Download Database : "**

2. Use horizontal space better on bootstrap.min.css

- For main page body, **reduce large margins on left and right**. Modify ".container" CSS style.
- For the 3 table columns: "Databases", "Tables", "Data", **reduce gap in between these columns**. Modify ".col-lg-1, ..." CSS style
- For first 2 columns in table: "Databases" and "Tables", **expand the width**. Modify ".col-sm-2" CSS style
- For 3rd table column "data", **make the column take the full width of page**, below the first 2 columns. Modify ".col-sm-8" CSS style

**Before screenshot of web page:**

1 before android_debug_database_-_2017-09-04_12 47

**After screenshot of web page:**

2 after android_debug_database_-_2017-09-04_13 13

### CODE REVIEW

**Comment by amitshekhariitbhu** [comment]
Great. Will check and merge it.
@vinayagasundar help me in verifying.

**Comment by ozmium** [comment]
Just a side note: I would recommend using a CSS formatter, to make it easier to edit and view the CSS files. Something like this: https://www.cleancss.com/css-beautify/

**Comment by vinayagasundar** [comment]
@amitshekhariitbhu I'll check it today.

**Comment by lyz19890927** [comment]
@ozmium I think it's necessary for javascript files too.

**Comment by vinayagasundar** [comment]
@amitshekhariitbhu I've verified the above request. 
It's working well.

**Comment by lorenzos** [comment]
IMHO moving data table under databases and tables list is a mistake. It moves data (i.e. what we care about) further down, making scrolling necessary 100% of times. The provided screenshot shows that clearly, also representing a "best but unreal scenario", since there are only 4 tables. and  Plus, it just moves the unused space from the right of data table, to the right of tables list.

I think a better solution is the one proposed in #50, where a dynamic layout is used to allow data table grow over empty screen space (that is, current left and right margin), leaving it where it already is.

**Comment by amitshekhariitbhu** [comment]
As it is not good for more number of tables. I am closing the PR.

**Pull request closed without merging**
